import { Preset } from '@/lib/types';

// デフォルト値を定義
const defaultNewProps = {
  textColor: 'rgba(255, 255, 255, 0.9)',
  shadowIntensity: 0.37,
  borderWidth: 1,
  glassNoise: false,
  responsive: true,
  // Size and spacing defaults
  width: 300,
  height: 200,
  margin: 16,
  maxWidth: 600,
};

export const defaultPresets: Preset[] = [
  // Original presets
  {
    id: 'modern',
    name: 'Modern Glass',
    config: {
      type: 'card',
      blur: 15,
      opacity: 0.25,
      saturation: 180,
      borderRadius: 12,
      backgroundColor: 'rgba(255, 255, 255, 0.25)',
      borderColor: 'rgba(255, 255, 255, 0.3)',
      padding: 24,
      animationEnabled: false,
      animationType: 'none',
      animationDuration: 2,
      animationDelay: 0,
      hoverEnabled: true,
      hoverEffect: 'lift',
      hoverIntensity: 1.2,
      hoverDuration: 0.3,
      ...defaultNewProps,
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'subtle',
    name: 'Subtle Glass',
    config: {
      type: 'card',
      blur: 8,
      opacity: 0.15,
      saturation: 120,
      borderRadius: 8,
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      borderColor: 'rgba(255, 255, 255, 0.2)',
      padding: 16,
      animationEnabled: false,
      animationType: 'none',
      animationDuration: 2,
      animationDelay: 0,
      hoverEnabled: true,
      hoverEffect: 'brightness',
      hoverIntensity: 1.1,
      hoverDuration: 0.2,
      ...defaultNewProps,
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bold',
    name: 'Bold Glass',
    config: {
      type: 'card',
      blur: 25,
      opacity: 0.4,
      saturation: 200,
      borderRadius: 16,
      backgroundColor: 'rgba(255, 255, 255, 0.4)',
      borderColor: 'rgba(255, 255, 255, 0.5)',
      padding: 32,
      animationEnabled: false,
      animationType: 'none',
      animationDuration: 2,
      animationDelay: 0,
      hoverEnabled: true,
      hoverEffect: 'scale',
      hoverIntensity: 1.05,
      hoverDuration: 0.4,
      ...defaultNewProps,
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },

  // Material Design inspired
  {
    id: 'material-light',
    name: '🎨 Material Light',
    config: {
      type: 'card',
      blur: 12,
      opacity: 0.2,
      saturation: 150,
      borderRadius: 8,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      borderColor: 'rgba(0, 0, 0, 0.12)',
      padding: 16,
      animationEnabled: true,
      animationType: 'float',
      animationDuration: 3,
      animationDelay: 0,
      hoverEnabled: true,
      hoverEffect: 'lift',
      hoverIntensity: 1.3,
      hoverDuration: 0.25,
      ...defaultNewProps,
      textColor: 'rgba(0, 0, 0, 0.87)',
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'material-dark',
    name: '🌙 Material Dark',
    config: {
      type: 'card',
      blur: 16,
      opacity: 0.3,
      saturation: 140,
      borderRadius: 8,
      backgroundColor: 'rgba(18, 18, 18, 0.8)',
      borderColor: 'rgba(255, 255, 255, 0.1)',
      padding: 20,
      animationEnabled: true,
      animationType: 'glow',
      animationDuration: 2,
      animationDelay: 0.5,
      hoverEnabled: true,
      hoverEffect: 'glow',
      hoverIntensity: 1.5,
      hoverDuration: 0.3,
      ...defaultNewProps,
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },

  // iOS inspired
  {
    id: 'ios-light',
    name: '🍎 iOS Light',
    config: {
      type: 'card',
      blur: 20,
      opacity: 0.8,
      saturation: 190,
      borderRadius: 12,
      backgroundColor: 'rgba(255, 255, 255, 0.8)',
      borderColor: 'rgba(0, 0, 0, 0.04)',
      padding: 20,
      animationEnabled: true,
      animationType: 'pulse',
      animationDuration: 2.5,
      animationDelay: 0,
      hoverEnabled: true,
      hoverEffect: 'cursor-follow',
      hoverIntensity: 0.8,
      hoverDuration: 0.2,
      ...defaultNewProps,
      textColor: 'rgba(0, 0, 0, 0.9)',
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ios-dark',
    name: '🌚 iOS Dark',
    config: {
      type: 'card',
      blur: 18,
      opacity: 0.75,
      saturation: 160,
      borderRadius: 12,
      backgroundColor: 'rgba(28, 28, 30, 0.75)',
      borderColor: 'rgba(255, 255, 255, 0.06)',
      padding: 20,
      animationEnabled: false,
      animationType: 'none',
      animationDuration: 2,
      animationDelay: 0,
      hoverEnabled: true,
      hoverEffect: 'brightness',
      hoverIntensity: 1.2,
      hoverDuration: 0.2,
      ...defaultNewProps,
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },

  // Windows 11 inspired
  {
    id: 'windows-acrylic',
    name: '🪟 Windows Acrylic',
    config: {
      type: 'card',
      blur: 30,
      opacity: 0.6,
      saturation: 120,
      borderRadius: 6,
      backgroundColor: 'rgba(243, 243, 243, 0.6)',
      borderColor: 'rgba(0, 0, 0, 0.08)',
      padding: 24,
      animationEnabled: true,
      animationType: 'shimmer',
      animationDuration: 4,
      animationDelay: 1,
      hoverEnabled: true,
      hoverEffect: 'scale',
      hoverIntensity: 1.02,
      hoverDuration: 0.2,
      ...defaultNewProps,
      textColor: 'rgba(0, 0, 0, 0.8)',
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'windows-mica',
    name: '💎 Windows Mica',
    config: {
      type: 'card',
      blur: 8,
      opacity: 0.9,
      saturation: 100,
      borderRadius: 4,
      backgroundColor: 'rgba(249, 249, 249, 0.9)',
      borderColor: 'rgba(0, 0, 0, 0.06)',
      padding: 20,
      animationEnabled: false,
      animationType: 'none',
      animationDuration: 2,
      animationDelay: 0,
      hoverEnabled: true,
      hoverEffect: 'lift',
      hoverIntensity: 1.1,
      hoverDuration: 0.15,
      ...defaultNewProps,
      textColor: 'rgba(0, 0, 0, 0.9)',
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },

  // Neomorphism inspired
  {
    id: 'neomorphism-light',
    name: '🔮 Neomorphism Light',
    config: {
      type: 'card',
      blur: 6,
      opacity: 0.1,
      saturation: 110,
      borderRadius: 20,
      backgroundColor: 'rgba(230, 230, 230, 0.1)',
      borderColor: 'rgba(255, 255, 255, 0.8)',
      padding: 24,
      animationEnabled: true,
      animationType: 'bounce',
      animationDuration: 1.5,
      animationDelay: 0,
      hoverEnabled: true,
      hoverEffect: 'cursor-tilt',
      hoverIntensity: 1.0,
      hoverDuration: 0.3,
      ...defaultNewProps,
      textColor: 'rgba(0, 0, 0, 0.8)',
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'neomorphism-dark',
    name: '🌑 Neomorphism Dark',
    config: {
      type: 'card',
      blur: 6,
      opacity: 0.15,
      saturation: 110,
      borderRadius: 20,
      backgroundColor: 'rgba(45, 45, 48, 0.15)',
      borderColor: 'rgba(255, 255, 255, 0.02)',
      padding: 24,
      animationEnabled: false,
      animationType: 'none',
      animationDuration: 2,
      animationDelay: 0,
      hoverEnabled: true,
      hoverEffect: 'glow',
      hoverIntensity: 1.3,
      hoverDuration: 0.4,
      ...defaultNewProps,
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },

  // Gaming/Cyberpunk inspired
  {
    id: 'cyberpunk',
    name: '🎮 Cyberpunk',
    config: {
      type: 'card',
      blur: 20,
      opacity: 0.3,
      saturation: 250,
      borderRadius: 4,
      backgroundColor: 'rgba(0, 255, 127, 0.1)',
      borderColor: 'rgba(0, 255, 255, 0.4)',
      padding: 20,
      animationEnabled: true,
      animationType: 'glow',
      animationDuration: 1,
      animationDelay: 0,
      hoverEnabled: true,
      hoverEffect: 'cursor-glow',
      hoverIntensity: 1.5,
      hoverDuration: 0.5,
      ...defaultNewProps,
      textColor: 'rgba(0, 255, 255, 0.9)',
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'gaming-rgb',
    name: '🌈 Gaming RGB',
    config: {
      type: 'card',
      blur: 15,
      opacity: 0.25,
      saturation: 300,
      borderRadius: 8,
      backgroundColor: 'rgba(138, 43, 226, 0.15)',
      borderColor: 'rgba(255, 0, 255, 0.3)',
      padding: 18,
      animationEnabled: true,
      animationType: 'shimmer',
      animationDuration: 2,
      animationDelay: 0,
      hoverEnabled: true,
      hoverEffect: 'cursor-follow',
      hoverIntensity: 1.8,
      hoverDuration: 0.3,
      ...defaultNewProps,
      textColor: 'rgba(255, 0, 255, 0.9)',
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },

  // Elegant/Premium
  {
    id: 'luxury-gold',
    name: '✨ Luxury Gold',
    config: {
      type: 'card',
      blur: 12,
      opacity: 0.2,
      saturation: 160,
      borderRadius: 10,
      backgroundColor: 'rgba(255, 215, 0, 0.1)',
      borderColor: 'rgba(255, 215, 0, 0.3)',
      padding: 28,
      animationEnabled: true,
      animationType: 'glow',
      animationDuration: 3,
      animationDelay: 0,
      hoverEnabled: true,
      hoverEffect: 'cursor-glow',
      hoverIntensity: 2.0,
      hoverDuration: 0.4,
      ...defaultNewProps,
      textColor: 'rgba(255, 215, 0, 0.9)',
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'platinum',
    name: '💫 Platinum',
    config: {
      type: 'card',
      blur: 18,
      opacity: 0.35,
      saturation: 130,
      borderRadius: 14,
      backgroundColor: 'rgba(229, 228, 226, 0.35)',
      borderColor: 'rgba(255, 255, 255, 0.4)',
      padding: 26,
      animationEnabled: true,
      animationType: 'float',
      animationDuration: 4,
      animationDelay: 0.5,
      hoverEnabled: true,
      hoverEffect: 'cursor-tilt',
      hoverIntensity: 1.08,
      hoverDuration: 0.6,
      ...defaultNewProps,
      textColor: 'rgba(64, 64, 64, 0.9)',
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },

  // Minimalist
  {
    id: 'ultra-minimal',
    name: '⚪ Ultra Minimal',
    config: {
      type: 'card',
      blur: 4,
      opacity: 0.05,
      saturation: 100,
      borderRadius: 2,
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderColor: 'rgba(0, 0, 0, 0.02)',
      padding: 12,
      animationEnabled: false,
      animationType: 'none',
      animationDuration: 2,
      animationDelay: 0,
      hoverEnabled: true,
      hoverEffect: 'cursor-follow',
      hoverIntensity: 1.5,
      hoverDuration: 0.1,
      ...defaultNewProps,
      textColor: 'rgba(0, 0, 0, 0.6)',
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'clean-border',
    name: '📐 Clean Border',
    config: {
      type: 'card',
      blur: 10,
      opacity: 0.12,
      saturation: 105,
      borderRadius: 0,
      backgroundColor: 'rgba(255, 255, 255, 0.12)',
      borderColor: 'rgba(0, 0, 0, 0.1)',
      padding: 16,
      animationEnabled: false,
      animationType: 'none',
      animationDuration: 2,
      animationDelay: 0,
      hoverEnabled: true,
      hoverEffect: 'lift',
      hoverIntensity: 1.15,
      hoverDuration: 0.2,
      ...defaultNewProps,
      textColor: 'rgba(0, 0, 0, 0.8)',
    },
    isPublic: true,
    usageCount: 0,
    createdAt: new Date().toISOString(),
  },
];